#todo: 部署需要修改数据库密码、图片存放位置、并且将图片打包发送至服务器
server:
  port: 8080
spring:
  application:
    name: zhaizhai
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://${host.mysql}:3306/zhaizhai?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${db.mysql.username}
      password: ${db.mysql.password}
  config:
    import: classpath:secret.yml
  redis:
    host: ${host.redis}
    password: ${db.redis.password}
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 8 # 最大连接数
        max-wait: 1ms # 连接池最大阻塞等待时间
        max-idle: 4 # 连接池中最大空闲连接
        min-idle: 0 # 连接池中最小空闲连接

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.alice.zhaizhai.pojo

zhaizhai:
  img-path: ${base-path}imgs/

tencent-cloud:
  sms:
    secret-id: ${sms.secret-id}
    secret-key: ${sms.secret-key}
    sdk-app-id: ${sms.sdk-app-id}
    sign-name: ${sms.sign-name}
    template-id: ${sms.template-id}


